Add arm code.
MiamiBeachBots/base-bot pull request #10
Opened 2023-02-12 18:22 UTC by jack60612

- [ ] Test on Robot
- [ ] Hold Arm stable
- [ ] Hold Arm stable while moving
- [ ]

2023-02-22 04:20 UTC, sviridovt requested changes

2023-02-22 04:20 UTC, sviridovt commented on src/main/java/frc/robot/commands/ArmCommand.java
> +    m_armSubsystem.armY(0.0, 0.0);
Lets not merge this until we can finalize these values

2023-02-28 08:15 UTC, sviridovt commented on src/main/java/frc/robot/RobotContainer.java
>    }
Are we resetting the odometry before initializing? ref https://github.com/mjansen4857/pathplanner/wiki/PathPlannerLib:-Java-Usage#ppramsetecommand

2023-02-28 12:24 UTC, jack60612 commented on src/main/java/frc/robot/DriveConstants.java
> +  public static final double Ka = 0.45481; // VoltSecondsSquaredPerMeter
i am going to re run the tests later today

2023-05-27 17:52 UTC, sviridovt approved these changes

2023-05-27 20:47 UTC, jack60612 commented
Yay well done @TimeToDie2 @sviridovt see you on Monday!

2023-05-27 20:47 UTC, merged