add all subsystems
MiamiBeachBots/base-bot pull request #3
Opened 2022-11-01 22:53 UTC by jack60612

2022-11-04 06:24 UTC, sviridovt requested changes

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/Robot.java
> +    cameraSelection = NetworkTableInstance.getDefault().getTable("").getEntry("CameraSelection");
Can we make camera into it's own subsystem?

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/Robot.java
> +                }));
Same as above

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/Robot.java
> +    // SmartDashboard.putNumber("Gyro angle", m_robotContainer.getGyro().getAngle());
Lets avoid committing commented code to mainline

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/commands/AutoCommand.java
> +  }
Should Shooter system be part of basebot?

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/commands/AutoCommand.java
> +      // m_robotContainer.doElevatorLift(-1);
Remove commented code

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/commands/AutoCommand.java
> +      timer_complete = true;
Lets try to keep basebot as general as possible, shooter system and auto code is game specific which I want to avoid in this package.

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/Robot.java
> +    // SmartDashboard.putNumber("Auto Sensor", getRangeInches(ultrasonic1));
SAA

2022-11-04 06:24 UTC, sviridovt commented on src/main/java/frc/robot/Robot.java
> +    SmartDashboard.putString("Commit", commitHash);
Nit, lets put it in a separate function with a proper docstring to keep things clean

2022-12-15 01:40 UTC, sviridovt approved these changes

2022-12-15 01:40 UTC, jack60612 commented
lets get this fully tested before merge.

2022-12-15 01:40 UTC, merged

2022-12-15 01:40 UTC, jack60612 commented
oh

2022-12-15 02:52 UTC, sviridovt commented
Assumed it was tested, let's test it on Monday and revert/amend if necessary. Sorry, should have asked

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jack Nelson ***@***.***>
Sent: Wednesday, December 14, 2022 8:41:02 PM
To: MiamiBeachBots/base-bot ***@***.***>
Cc: sviridovt ***@***.***>; State change ***@***.***>
Subject: Re: [MiamiBeachBots/base-bot] add all subsystems & add default drive + robot bare min (PR #3)


oh

—
Reply to this email directly, view it on GitHub<https://github.com/MiamiBeachBots/base-bot/pull/3#issuecomment-1352447136>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AASRZDJQELWYHXDRIOKDRVDWNJZK5ANCNFSM6AAAAAARUQNMFM>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>